from __future__ import annotations

import argparse
from pathlib import Path

from src.core.io_utils import read_json
from src.eval.placeholder_scan import scan_placeholders


def _validate_claim_matrix(path: Path, outputs_root: Path) -> None:
    lines = path.read_text(encoding="utf-8").splitlines()
    for line in lines:
        if not line.startswith("| C"):
            continue
        cells = [cell.strip() for cell in line.strip("|").split("|")]
        if len(cells) != 3:
            continue
        claim_id, evidence, status = cells
        if claim_id == "Claim":
            continue
        if status == "pending":
            raise ValueError("Claim evidence matrix still contains pending rows")
        if evidence == "none":
            continue
        for rel_path in [entry.strip() for entry in evidence.split(",")]:
            if not (outputs_root / rel_path).exists():
                raise ValueError(f"Claim evidence matrix references a missing artifact: {rel_path}")


def write_paper(outputs_root: Path, template_path: Path) -> Path:
    paper_dir = Path("paper")
    paper_dir.mkdir(parents=True, exist_ok=True)
    claim_matrix = outputs_root / "paper_assets" / "appendix" / "claim_evidence_matrix.md"
    _validate_claim_matrix(claim_matrix, outputs_root)
    title = "ProbeRoute Progress Report"
    abstract = "This draft is generated from the current artifact set and should be refined as mandatory runs complete."
    template = template_path.read_text(encoding="utf-8")
    content = template.replace("{TITLE}", title).replace("{ABSTRACT}", abstract)
    content += "\n\n## Appendix Reference\n"
    content += f"- Claim evidence matrix: {claim_matrix}\n"
    draft_path = paper_dir / "paper_draft.md"
    draft_path.write_text(content, encoding="utf-8")
    unresolved = scan_placeholders(draft_path)
    if unresolved:
        raise ValueError(f"Unresolved placeholders remain in paper draft: {unresolved}")
    final_delivery = Path("FINAL_DELIVERY.md")
    final_delivery.write_text(
        "\n".join(
            [
                "# Final Delivery",
                "",
                "This delivery note was autogenerated from the current scaffold state.",
                f"- Outputs root: {outputs_root}",
                f"- Paper draft: {draft_path}",
                f"- Claim evidence matrix: {claim_matrix}",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    return draft_path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--outputs-root", required=True)
    parser.add_argument("--template", required=True)
    args = parser.parse_args()
    path = write_paper(Path(args.outputs_root).resolve(), Path(args.template).resolve())
    print(path)


if __name__ == "__main__":
    main()
